#!/bin/bash

DefaultWorkingDir=$(pwd)

usage() {
	echo "usage: 02_TangentXY.sh -d <WorkingDir> -s <SIF> -n <NormalsMatrix> -p <NormalsTransformedMatrix> -t <TumorMatrix> -l <LatentFactorNum>"

	echo "  WorkingDir: Working directory. 'output' directory is automatically generated under this directory."
	echo "  SIF: Sample information file."
	echo "  NormalsMatrix: Normal sample signal matrix file with the values in log2(Relative Copy Number) format."
	echo "  NormalsTransformedMatrix: RData file generated by 01_PreprocessNormals.sh."
	echo "  TumorMatrix: Tumor sample signal matrix file with the values in log2(Relative Copy Number) format."
	echo "  LatentFactorNum: The number of latent factors to reconstruct a normal subspace. Need to be less than or equal to the number of normal samples in the normal sample signal matrix."
}

while getopts :d:s:n:p:t:l: option; do
	case "${option}" in
		d) WorkingDir=${OPTARG};;
		s) SIF=${OPTARG};;
		n) NormalsMatrix=${OPTARG};;
		p) NormalsTransformedMatrix=${OPTARG};;
		t) TumorsMatrix=${OPTARG};;
		l) LatentFactorNum=${OPTARG};;
		\?)
				echo "Unknown options:"
				usage
				exit 1;;
		:)
				echo "Missing required options:"
				usage
				exit 1;;
		h|*)
				usage
				exit 1;;
	esac
done

if [ -z ${SIF} ] || [ -z ${NormalsMatrix} ] || [ -z ${NormalsTransformedMatrix} ] || [ -z ${TumorsMatrix} ] || [ -z ${LatentFactorNum} ]; then
	echo "Key arguments (Sample information file, Normal samples matrix, Normal samples transformed matrix, Tumor samples matrix, Number of latentfactors) not present."
	usage
	exit 1
else
	SIF_Absolute=$(realpath ${SIF})
	NormalsMatrix_Absolute=$(realpath ${NormalsMatrix})
	NormalsTransformedMatrix_Absolute=$(realpath ${NormalsTransformedMatrix})
	TumorsMatrix_Absolute=$(realpath ${TumorsMatrix})
fi

if [ -z ${WorkingDir} ]; then
	WorkingDir=${DefaultWorkingDir}
	WorkingDir_Absolute=$(realpath ${WorkingDir})
	echo "Working directory not set. Using "${WorkingDir_Absolute}" instead."
else
	WorkingDir_Absolute=$(realpath ${WorkingDir})
	echo "Working directory = "${WorkingDir_Absolute}
fi


echo -e "\nRunning TangentXY...\n"

Rscript --slave ./module/03_TangentXY.R \
	-d ${WorkingDir_Absolute} -s ${SIF_Absolute} -n ${NormalsMatrix_Absolute} -p ${NormalsTransformedMatrix_Absolute} -t ${TumorsMatrix_Absolute} -l ${LatentFactorNum}

